#! /bin/sh
# Script to shut down a network (tap) device for qemu.
# Initially this script is empty, but you can configure,
# for example, accounting info here.

BRIDGE="virbr0"

if [ -n "$1" ]; then
	echo "Tearing down networking bridge for $1"
	ip link set $1 down
	brctl delif "$BRIDGE" $1
	ip link set "$BRIDGE" down
	brctl delbr "$BRIDGE"
	iptables -t nat -F
	exit 0
else
	echo "Error: no interface specified"
	exit 1
fi
